name: MacOS Build and Release

on:
  push:
    branches: [ "main" ]

jobs:
  build:
    name: Build Neko Gui
    runs-on:  macos-15

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Build NekoGui
        env:
          APPLE_TEAM_ID:  ${{ secrets.APPLE_TEAM_ID }}
        run: xcodebuild -scheme NekoGui -configuration Pre -derivedDataPath "$RUNNER_TEMP/DerivedData" -archivePath "$RUNNER_TEMP/NekoGui.xcarchive" -skipPackagePluginValidation DEVELOPMENT_TEAM=$APPLE_TEAM_ID archive | xcpretty

      - name: Clean up keychain and provisioning profile
        if: ${{ always() }}
        run: |
          security delete-keychain "$RUNNER_TEMP/keychain.keychain-db"
          rm -rf "~/Library/MobileDevice/Provisioning Profiles"
